repos:
  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: v2.0.1
    hooks:
      - id: dbt-compile
        args: ["--cmd-flags", "++project-dir", "dbt_service/","++profiles-dir", "/Users/mahmoud/.dbt/", "++no-version-check", "--model-prefix", "+", "--"]
      - id: check-script-semicolon
      - id: dbt-docs-generate
        args: ["--cmd-flags", "++project-dir", "dbt_service/","++profiles-dir", "/Users/mahmoud/.dbt/", "++no-version-check", ]
        files: dbt_service/
        

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.0.6
    hooks:
      - id: sqlfluff-lint
        additional_dependencies: ["dbt-snowflake==1.8.0", "sqlfluff-templater-dbt==3.0.6"]
        types: [sql]
        exclude: "^target/"
        args: [--config, ".sqlfluff",
          --processes, "10"]